### ISSUE TITLE
No element in the source document matches '/configuration/umbracoConfiguration'

### ISSUE THREAD

**Issue by gvcayetano** [rhythmagency/formulate#103]
Hi all, I'm getting this error on my UmbracoTracelog.log

Umbraco version 7.4.2
Formulate version 1.3.4.0

any idea what's causing it?

Thanks!
>  2017-08-14 07:43:08,031 [P18804/D15/T206] ERROR umbraco.cms.businesslogic.packager.PackageAction - Error loading package action 'Formulate.TransformXmlFile' for package Formulate
Microsoft.Web.XmlTransform.XmlNodeException: No element in the source document matches '/configuration/umbracoConfiguration' ---> Microsoft.Web.XmlTransform.XmlTransformationException: No element in the source document matches '/configuration/umbracoConfiguration'
   at Microsoft.Web.XmlTransform.InsertBase.get_SiblingElement()
   at Microsoft.Web.XmlTransform.InsertAfter.Apply()
   at Microsoft.Web.XmlTransform.Transform.ApplyOnce()
   at Microsoft.Web.XmlTransform.Transform.Execute(XmlElementContext context, String argumentString)
   --- End of inner exception stack trace ---
   at Microsoft.Web.XmlTransform.XmlTransformationLogger.LogErrorFromException(Exception ex)
   at Microsoft.Web.XmlTransform.XmlTransformation.Apply(XmlDocument xmlTarget)
   at formulate.app.Install.Package_Actions.TransformXmlFile.Transform(XmlNode xmlData, Boolean install) in C:\Projects\formulate\src\formulate.app\Install\Package_Actions\TransformXmlFile.cs:line 123
   at formulate.app.Install.Package_Actions.TransformXmlFile.Execute(String packageName, XmlNode xmlData) in C:\Projects\formulate\src\formulate.app\Install\Package_Actions\TransformXmlFile.cs:line 64
   at umbraco.cms.businesslogic.packager.PackageAction.RunPackageAction(String packageName, String actionAlias, XmlNode actionXml)

**Comment by Nicholas-Westby** [comment]
That's strange, it seems like your web.config may be missing a `<umbracoConfiguration>` element. You can see an example here: https://github.com/rhythmagency/formulate/blob/65f7659cce8ad92c973e904cf49eb44194c4532a/src/Website/web.sample.config#L17

Does your web.config have that? Can you paste your web.config here, excluding any sensitive information (e.g., credentials, such as the connection string)?

**Comment by Nicholas-Westby** [comment]
Closing this issue under the assumption that you've figured it out. If that's not the case, feel free to let me know and I can reopen it.

**Comment by biapar** [comment]
I've a similar problem on Umbraco 7.6.5 https://github.com/rhythmagency/formulate/issues/105
