### ISSUE TITLE
Umbraco 7.6.5: Error install Formulate

### ISSUE THREAD

**Issue by biapar** [rhythmagency/formulate#105]
I tried to install on Umbraco 7.6.5 but the system give the error:

```
Error loading package action 'Formulate.TransformXmlFile' for package Formulate
System.IO.FileNotFoundException: Could not find file 'C:\Hosting\www.xcdfdfdf.xzs\App_Plugins\formulate\Transforms\dashboard.config.install.xdt'.
File name: 'C:\Hosting\www.xcdfdfdf.xzs\App_Plugins\formulate\Transforms\dashboard.config.install.xdt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Boolean detectEncodingFromByteOrderMarks)
   at Microsoft.Web.XmlTransform.XmlFileInfoDocument.LoadFromFileName(String filename)
   at Microsoft.Web.XmlTransform.XmlFileInfoDocument.Load(String filename)
   at Microsoft.Web.XmlTransform.XmlTransformation..ctor(String transform, Boolean isTransformAFile, IXmlTransformationLogger logger)
   at formulate.app.Install.Package_Actions.TransformXmlFile.Transform(XmlNode xmlData, Boolean install) in C:\Projects\formulate\src\formulate.app\Install\Package_Actions\TransformXmlFile.cs:line 119
   at formulate.app.Install.Package_Actions.TransformXmlFile.Execute(String packageName, XmlNode xmlData) in C:\Projects\formulate\src\formulate.app\Install\Package_Actions\TransformXmlFile.cs:line 65
   at umbraco.cms.businesslogic.packager.PackageAction.RunPackageAction(String packageName, String actionAlias, XmlNode actionXml)
```

**Comment by Nicholas-Westby** [comment]
I will give it a try when I get home, but my guess is this is some sort of permission issue on your machine (i.e., I expect I will be unable to reproduce the issue). IIRC, the transforms haven't been significantly modified in a good while.

In the meantime, can you answer these questions:

* Which version of Formulate?
* Is this a new install of Formulate, or was Formulate already installed?
* Are you installing Formulate with NuGet, or with the download from the package page on our.umbraco.org?
* Are you installing it on your local computer, or via a website that is already on a web host (e.g., GoDaddy)?
* Have you tried this with a clean install of Umbraco 7.6.5?

**Comment by Nicholas-Westby** [comment]
Additional question:

* Assuming you are using Visual Studio, is your website setup as a "Website" or a "Web Application" (in the Visual Studio project type sense)?

**Comment by biapar** [comment]
Hi,

- v 1.3.5
- new install
- Installed with package file or by Umbrac backend
- Website
- I installed it on clean Umbraco with new default starter kit
- In this case I did'nt used Vs.

**Comment by Nicholas-Westby** [comment]
Wasn't able to look into this yet. Will try again tomorrow/this weekend.

**Comment by Nicholas-Westby** [comment]
I wasn't able to reproduce your error. I was able to install the latest Formulate (1.3.5) on the latest Umbraco (7.6.5) without issue:

![formulate](https://user-images.githubusercontent.com/5933222/29735048-c8d79052-89aa-11e7-9db7-c4ec7dce924d.png)

My guess is this is a permission issue or something else peculiar about your setup. By chance, is your Umbraco install in a subfolder under your main domain rather than at the root of your domain?

**Comment by biapar** [comment]
Sigh.
It's installed in the root.

**Comment by Nicholas-Westby** [comment]
Have you tried removing all remnants of the install (perhaps it got interrupted for some reason) and trying to install again?

**Comment by garyhammett** [comment]
Looks like you may need to give the IIS user permission to C:\windows\temp.

That fixed that install issue for me.

**Comment by Nicholas-Westby** [comment]
@garyhammett I've never had to do that, and I can't think of anything specific to Formulate that would use that folder (other than the Umbraco installer, though I believe that uses the `~/App_Data/TEMP` folder). How'd you come to the conclusion that you should give IIS permission to that folder?

**Comment by garyhammett** [comment]
Hi @Nicholas-Westby,

For me this wasn't tied to your extention. I couldn't install any package. I ran it through IIS locally and the moment I added this permission it installed. 

Like @biapar I checked logs and had the same issue. I'm using the latest version as of today. It was also a fresh laptop so didn't have some of these things applied to it yet.
