### ISSUE TITLE
v3.7.0 - Installation is broken

### ISSUE THREAD

**Issue by hyrmedia** [rhythmagency/formulate#62]
When I install v3.7.0, it doesn't add Formulate to the applications.config, and it doesn't add the Formulate tab to the Developer section.

I added these manually. Now when I click 'Formulate' on the backoffice sidebar, I get the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.

at formulate.app.Managers.DefaultConfigurationManager.get_JsonBasePath() in C:\r\formulate\src\formulate.app\Managers\DefaultConfigurationManager.cs:line 29
   at formulate.app.Persistence.Internal.JsonFolderPersistence.get_BasePath() in C:\r\formulate\src\formulate.app\Persistence\Internal\JsonFolderPersistence.cs:line 71
   at formulate.app.Persistence.Internal.JsonFolderPersistence.get_Helper() in C:\r\formulate\src\formulate.app\Persistence\Internal\JsonFolderPersistence.cs:line 41
   at formulate.app.Persistence.Internal.JsonFolderPersistence.RetrieveChildren(Nullable`1 parentId) in C:\r\formulate\src\formulate.app\Persistence\Internal\JsonFolderPersistence.cs:line 165
   at formulate.app.Persistence.Internal.DefaultEntityPersistence.RetrieveChildren(Nullable`1 parentId) in C:\r\formulate\src\formulate.app\Persistence\Internal\DefaultEntityPersistence.cs:line 164
   at formulate.app.Trees.FormulateTreeController.GetTreeNodes(String id, FormDataCollection queryStrings) in C:\r\formulate\src\formulate.app\Trees\FormulateTreeController.cs:line 187
   at Umbraco.Web.Trees.TreeControllerBase.GetNodes(String id, FormDataCollection queryStrings) in D:\src\Applications\UmbracoCms-SRC\src\Umbraco.Web\Trees\TreeControllerBase.cs:line 113
   at Umbraco.Web.Trees.ApplicationTreeExtensions.TryLoadFromControllerTree(ApplicationTree appTree, String id, FormDataCollection formCollection, HttpControllerContext controllerContext) in D:\src\Applications\UmbracoCms-SRC\src\Umbraco.Web\Trees\ApplicationTreeExtensions.cs:line 144
   at Umbraco.Web.Trees.ApplicationTreeController.<GetRootForSingleAppTree>d__2.MoveNext() in D:\src\Applications\UmbracoCms-SRC\src\Umbraco.Web\Trees\ApplicationTreeController.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Umbraco.Web.Trees.ApplicationTreeController.<GetApplicationTrees>d__0.MoveNext() in D:\src\Applications\UmbracoCms-SRC\src\Umbraco.Web\Trees\ApplicationTreeController.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()```

**Comment by Nicholas-Westby** [comment]
Thanks for the report!

It sounds like the install process didn't complete. I have noticed this happen before (there seems to be a bug in the Umbraco core that sometimes prevents full installation of some packages). In my case, I simply installed Formulate again and it worked fine after that.

Can you try installing Formulate again to see if that fixes things?

If it doesn't, could you let me know which Umbraco version you are using, as well as the specific steps you are taking to install Formulate?

**Comment by Nicholas-Westby** [comment]
By the way, I think newer versions (e.g., 7.5.3) of Umbraco prevent you from installing the same package version twice. If that's true, you may have to do some work to trick Umbraco into thinking it hasn't been installed yet (e.g., you may have to remove it from the installed packages XML file).

**Comment by hyrmedia** [comment]
It's been my experience in 7.5.3 that once you "Uninstall" a package you can go ahead and reinstall it again.

However, I've installed, uninstalled, and reinstalled the package on two different instances of Umbraco. Same result every time.

**Comment by Nicholas-Westby** [comment]
Thanks for the quick follow up. I will see if I can reproduce this. In the meantime, can you give me a list of steps for how you are installing Formulate?

**Comment by hyrmedia** [comment]
I've tried installing both via the new backoffice package catalog, and also by downloading it from Our and using "Install Local".

I'm not sure if this is specifically the problem yet, but I noticed that Formulate 3.7.0 is dependent upon .NET 4.5.2. In particular you are using `HostingEnvironment.QueueBackgroundWorkItem` in the ApplicationStartedHandler, which is only available in 4.5.2.

My Umbraco project currently has to be .NET 4.5 for compatibility reasons. This is also the requirement for Umbraco, and most packages respect this min. version. I would strongly suggest finding an alternate approach here.

Thanks!

**Comment by Nicholas-Westby** [comment]
I think you are correct. Formulate does indeed require .Net 4.5.2: http://www.formulate.rocks/requirements

If you are unable to upgrade to .NET 4.5.2, I suppose you could create a custom build of Formulate that doesn't make use of `QueueBackgroundWorkItem`. Building Formulate is a fairly simple process, which is outlined here: https://github.com/rhythmagency/formulate#building

**Comment by hyrmedia** [comment]
Just to be clear, I DO have .NET 4.5.2 installed. It's just that my Umbraco web app project targets .NET 4.5.

**Comment by Nicholas-Westby** [comment]
Can you try changing your project to target .NET 4.5.2?

**Comment by Nicholas-Westby** [comment]
Just a thought that this could possibly be related to this core bug in Umbraco 7.5.3: http://issues.umbraco.org/issue/U4-8981

**Comment by Nicholas-Westby** [comment]
@hyrmedia FYI, I just tested this and was able to install Formulate 0.3.7.0 on Umbraco 7.5.3 without issue. Perhaps you were right about it being a .NET version mismatch. For reference, here are all the lines in my Umbraco log that mention Formulate:

```
 2016-10-19 13:54:53,275 [P2876/D15/T18] INFO  formulate.app.Handlers.ApplicationStartedHandler - Installing Formulate.
 2016-10-19 13:54:57,843 [P2876/D17/T1] INFO  formulate.app.Handlers.ApplicationStartedHandler - Installing Formulate.
 2016-10-19 13:55:04,331 [P2876/D19/T1] INFO  formulate.app.Handlers.ApplicationStartedHandler - Installing Formulate.
 2016-10-19 13:55:13,293 [P2876/D15/T29] INFO  formulate.app.Handlers.ApplicationStartedHandler - Running the queue of Formulate install actions.
 2016-10-19 13:55:13,325 [P2876/D15/T29] INFO  formulate.app.Handlers.ApplicationStartedHandler - Installing Formulate section in applications.config.
 2016-10-19 13:55:13,375 [P2876/D15/T29] INFO  formulate.app.Handlers.ApplicationStartedHandler - Done installing Formulate section in applications.config.
 2016-10-19 13:55:13,413 [P2876/D15/T29] INFO  formulate.app.Handlers.ApplicationStartedHandler - Installing Formulate developer tab.
 2016-10-19 13:55:13,440 [P2876/D15/T29] INFO  formulate.app.Handlers.ApplicationStartedHandler - Done installing Formulate developer tab.
 2016-10-19 13:55:13,444 [P2876/D15/T29] INFO  formulate.app.Handlers.ApplicationStartedHandler - Adding Formulate config to the web.config.
 2016-10-19 13:55:13,514 [P2876/D15/T29] INFO  formulate.app.Handlers.ApplicationStartedHandler - Done adding Formulate config to the web.config.
 2016-10-19 13:55:13,516 [P2876/D15/T29] INFO  formulate.app.Handlers.ApplicationStartedHandler - Ensuring Formulate version in the web.config.
 2016-10-19 13:55:13,554 [P2876/D15/T29] INFO  formulate.app.Handlers.ApplicationStartedHandler - Done ensuring Formulate version in the web.config.
 2016-10-19 13:55:13,554 [P2876/D15/T29] INFO  formulate.app.Handlers.ApplicationStartedHandler - Done running the queue of Formulate install actions.
 2016-10-19 13:55:17,929 [P2876/D17/T36] INFO  formulate.app.Handlers.ApplicationStartedHandler - Running the queue of Formulate install actions.
 2016-10-19 13:55:17,941 [P2876/D17/T36] INFO  formulate.app.Handlers.ApplicationStartedHandler - Installing Formulate section in applications.config.
 2016-10-19 13:55:18,121 [P2876/D17/T36] INFO  formulate.app.Handlers.ApplicationStartedHandler - Done installing Formulate section in applications.config.
 2016-10-19 13:55:18,149 [P2876/D17/T36] INFO  formulate.app.Handlers.ApplicationStartedHandler - Ensuring Formulate version in the web.config.
 2016-10-19 13:55:18,190 [P2876/D17/T36] INFO  formulate.app.Handlers.ApplicationStartedHandler - Done ensuring Formulate version in the web.config.
 2016-10-19 13:55:18,190 [P2876/D17/T36] INFO  formulate.app.Handlers.ApplicationStartedHandler - Done running the queue of Formulate install actions.
 2016-10-19 13:55:24,351 [P2876/D19/T24] INFO  formulate.app.Handlers.ApplicationStartedHandler - Running the queue of Formulate install actions.
 2016-10-19 13:55:24,351 [P2876/D19/T24] INFO  formulate.app.Handlers.ApplicationStartedHandler - Installing Formulate section in applications.config.
 2016-10-19 13:55:24,446 [P2876/D19/T24] INFO  formulate.app.Handlers.ApplicationStartedHandler - Done installing Formulate section in applications.config.
 2016-10-19 13:55:24,463 [P2876/D19/T24] INFO  formulate.app.Handlers.ApplicationStartedHandler - Ensuring Formulate version in the web.config.
 2016-10-19 13:55:24,491 [P2876/D19/T24] INFO  formulate.app.Handlers.ApplicationStartedHandler - Done ensuring Formulate version in the web.config.
 2016-10-19 13:55:24,491 [P2876/D19/T24] INFO  formulate.app.Handlers.ApplicationStartedHandler - Done running the queue of Formulate install actions.
```

Seems to be a few things repeated for whatever reason, but worked in the end.

Once you check your log, you might want to take a look at file system permissions.
